brzirecepti/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # /admin/ - admin interfejs
    path('admin/', admin.site.urls),

    path('', include('recepti.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recepti/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    # pocetna stranica
    path('', views.IndexView.as_view(), name='index'),

    # stranica koja ce prikazivati recepte koje je moguce napraviti
    path('recepti/', views.ReceptiView.as_view(), name='recepti'),

    # stranica recepta
    path('recepti/<int:pk>/', views.DetailView.as_view(), name='detalji'),

    # stranica za registraciju
    path('registracija/', views.UserFormView.as_view(), name='registracija'),

    # prijavljivanje i odjavljivanje
    path('login/', auth_views.LoginView.as_view, {'template_name': 'recepti/login.html'}, name='prijavljivanje'),
    path('logout/', auth_views.LogoutView.as_view, {'next_page': '/'}, name='odjavljivanje'),

    # dodaj recept
    path('dodajrecept/', views.DodajView.as_view(), name='dodajrecept'),

    # zdrava ishrana
    path('zdravaishrana/', views.ZdravaIshranaView.as_view(), name='zdravaishrana'),
    # pdf
    # path('pdf/', views.GeneratePdf.as_view()),
]

recepti/models.py
from django.db import models


class Kategorije(models.Model):                                               # dorucak, rucak, vecera, dezert
    ime = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Kategorije"

    def __str__(self):
        return self.ime


class Sastojci(models.Model):                                                 # npr mrkva, kupus, krompir, banana...
    ime = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Sastojci"

    def __str__(self):
        return self.ime


class Jela(models.Model):
    ime = models.CharField(max_length=100)
    slika = models.FileField()
    kategorija = models.ForeignKey(Kategorije, on_delete=models.CASCADE, null=True)  # Doručak, Ručak, Večera, Užina
    sastojci = models.ManyToManyField(Sastojci)
    sastojci_opis = models.TextField(null=True)
    nacin_pripreme = models.TextField()
    je_vegeterijansko = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Jela"

    def __str__(self):
        return self.ime

recepti/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Jela


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class DodajRecept(forms.ModelForm):
    class Meta:
        model = Jela
        fields = ['ime', 'slika', 'kategorija', 'sastojci', 'sastojci_opis', 'nacin_pripreme', 'je_vegeterijansko']

class SastojciL(forms.Form):
    q = forms.CharField()

recepti/views.py
from django.views import generic
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from django.contrib import messages
from .models import Jela, Sastojci
from .forms import UserForm, DodajRecept, SastojciL
from django.http import HttpResponse

from django.db.models import OuterRef


# from django.http import HttpResponse
# from .utils import render_to_pdf


class IndexView(generic.ListView):  # pocetna
    template_name = 'recepti/index.html'
    model = Jela

    def get(self, request):
        return render(request, self.template_name, {'form': SastojciL()})

    def post(self, request):
        if request.method == 'POST':
            form = SastojciL(request.POST)
            if form.is_valid():
                tagovi = form.cleaned_data['q']
                return redirect('recepti')
            else:
                pass
            return render(request, self.template_name, {'form': SastojciL()})


class ReceptiView(generic.ListView):
    template_name = 'recepti/recepti.html'
    context_object_name = 'recepti'

    # because of context_object_name above and how generic.ListView works,
    # the result of this is available in your template as {{ recepti }}

    def get_queryset(self):
        return Jela.objects.filter(sastojci__ime__icontains="Jaja")

    # def get_queryset(self):
    #     query = Jela.objects \
    #                 .annotate(
    #                     contains_other=OuterRef(
    #                         Sastojci.objects.filter(jela=OuterRef('pk')).exclude(
    #                             ime__in=('Jaja', 'Krompir')
    #                         )
    #                     )
    #                  ) \
    #                .filter(contains__other=False)
    #     return query

    # the : str and -> Jela are type hints, they show what kind of data type the input/output have
    def get_random(self, category: str) -> Jela:
        # we can re-use the base queryset to further filter, and for that we can just call existing methods again
        queryset = self.get_queryset()
        return queryset.filter(kategorija__ime=category).order_by('?').first()

    # this provides all the extra context you want in your template that
    # is not 'automagically' generated by django's generic views
    def get_context_data(self, **kwargs):
        # you need to call the parent method to get all the 'default' stuff from django's generic view
        context = super().get_context_data(**kwargs)
        context.update({
            'random_dorucak': self.get_random('Doručak'),
            'random_rucak': self.get_random('Ručak'),
            'random_vecera': self.get_random('Večera'),
            'random_uzina': self.get_random('Užina'),
        })
        return context


class DetailView(generic.DetailView):  # detalji recepta
    context_object_name = 'jelo'
    model = Jela
    template_name = 'recepti/detail.html'


class ZdravaIshranaView(generic.ListView):  # zdrava ishrana
    context_object_name = 'zdravaishrana'
    model = Jela
    template_name = 'recepti/zdravaishrana.html'


class UserFormView(View):
    form_class = UserForm
    template_name = 'recepti/registration_form.html'

    def get(self, request):  # display blank form
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):  # process form data
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return User objects if credentials are correct

            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('index')

        return render(request, self.template_name, {'form': form})


class DodajView(View):
    template_name = 'recepti/dodajrecept.html'

    def get(self, request):
        return render(request, self.template_name, {'form': DodajRecept()})

    def post(self, request):
        if request.method == 'POST':
            form = DodajRecept(request.POST, request.FILES)
            if form.is_valid():
                form.save(commit=True)
                return redirect('index')
            else:
                messages.error(request, form)
            return render(request, self.template_name, {'form': DodajRecept()})


# class GeneratePdf(View):  # za kreiranje pdf fajlova
#
#     def get(self, request):
#         context = {
#             'jelo.ime': "dfaljsdf asdf asd f",
#             "jelo.sastojci_opis | linebreaks": "asdf afffff",
#             "jelo.nacin_pripreme | linebreaks": "aaaaaaaaaaaaaaaaa",
#         }
#         pdf = render_to_pdf('invoice.html', context)
#
#         if pdf:
#             response = HttpResponse(pdf, content_type='application/pdf')
#             filename = "Invoice_%s.pdf" % ("12341231")
#             content = "inline; filename='%s'" % (filename)
#             download = request.GET.get("download")
#             if download:
#                 content = "attachment; filename='%s'" % (filename)
#             response['Content-Disposition'] = content
#             return response
#         return HttpResponse("Not found")

recepti/templates/invoice.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
 <html>
     <head>
         <title>{{jelo.ime}}</title>
     </head>
     <body>
          <div class="container">
                <div class="ime">
                 <h> {{jelo.ime}} </h>
                </div>
                <div class="sastojci">
                    <p> {{jelo.sastojci_opis|linebreaks}}</p>
                </div>
                <div class="priprema">
                    <p> {{jelo.nacin_pripreme|linebreaks}}</p>
                </div>
          </div>
     </body>
 </html>

recepti/templates/recepti/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <!--bootstrap, js and jquery-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--custom - style.css, favicon and font-->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'recepti/style.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">

</head>
<body>

    <!--navbar-->
    <nav class="navbar navbar-expand-lg">

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse .col-xs-6 .col-sm-3" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">POČETNA <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dodajrecept' %}">DODAJ RECEPT</a>
          </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'zdravaishrana' %}">ZDRAVA ISHRANA</a>
          </li>
        </ul>
      </div>

    <div class="slika .col-xs-6 .col-sm-3" style="margin-left: 354px;">
          <img class="mx-auto img-fluid" src="/static/recepti/images/logo.png">
      </div>

      <div class="region-navbar-3 .col-xs-6 .col-sm-4">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                  <a href="{% url 'odjavljivanje' %}" class="btn btn-lg btn-success" style="background: #dcdfe5; border-color: #FA1423;">ODJAVI SE</a>
                {% else %}
                  <a href="{% url 'prijavljivanje' %}" class="btn btn-lg btn-success" style="background: #dcdfe5; border-color: #FA1423;">PRIJAVI SE</a>
                {% endif %}
            </li>
        </ul>
      </div>

    </nav>


{% block body %}
{% endblock %}

</body>
</html>

recepti/templates/recepti/detail.html
{% extends 'recepti/base.html' %}
{% block title %}{{jelo.ime}}{% endblock %}
{% load staticfiles %}

{% block body %}

  <link rel="stylesheet" type="text/css" href="{% static 'recepti/detail.css' %}" >

    <div class="container">
        <div class="ime">
         <h> {{jelo.ime}} </h>
        </div>
         <div class="slika">
             <img src="{{jelo.slika.url}}" class="slikajela" width="600" height="400">
        </div>
         <div class="recept">
            <div class="sastojci">
                <P class="prvi" style="font-weight: bold;">SASTOJCI</P>
                <p> {{jelo.sastojci_opis|linebreaks}}</p>
            </div>
            <div class="priprema">
                <P class="drugi" style="font-weight: bold;">PRIPREMA</P>
                <p> {{jelo.nacin_pripreme|linebreaks}}</p>
            </div>
         </div>
    </div>

{% endblock %}

recepti/templates/recepti/dodajrecept.html
{% extends 'recepti/base.html' %}
{% block title %}Dodaj recept!{% endblock %}
{% load staticfiles %}

{% block body %}
    <link rel="stylesheet" type="text/css" href="{% static 'recepti/dodajrecept.css' %}" >
    <div class="divcina">

            {% if form.errors %}
                 {% for field in form %}
                    {% for error in field.errors %}
                         <div class="badge badge-warning">
                         <strong>{{ error|escape }}</strong>
                         </div><br/>
                    {% endfor %}
                 {% endfor %}
                 {% for error in form.non_field_errors %}
                        <div class="badge badge-warning">
                        <strong>{{ error|escape }}</strong>
                         </div><br/>
                {% endfor %}
            {% endif %}
            <form action="{% url 'dodajrecept' %}" method="post" enctype="multipart/form-data">
                {% csrf_token  %}
                       {{form.as_p}}
                <input type="submit" value="Dodaj!"
                       class="btn-primary" />
            </form>
    </div>
{% endblock %}

recepti/templates/recepti/form_template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

recepti/templates/recepti/index.html
{% extends 'recepti/base.html' %}
{% block title %}Brzi-Recepti{% endblock %}
{% load staticfiles %}

{% block body %}

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="{% static 'recepti/js/tag-it.js' %}" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
    <link href="{% static 'recepti/jquery.tagit.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'recepti/index.css' %}" >

    <div class="div">
        <div class="blur">
            <h1 align="center" style="color:white; font-weight: 1000;">PRONAĐITE RECEPTE</h1>

            <script type="text/javascript">
                $(document).ready(function() {
                    $("#myTags").tagit();
                    $("#search-form").submit(function(e) {
                        var all = $(".tagit-label").map(function() {
                            return this.innerHTML;
                        }).get();

                        var tags = all.join();
                        $("#id_q").val(tags);

                         // alert(tags);
                    });
                    $("#myTags").tagit({ availableTags: ["Ulje","Mliječna čokolada","Slatka pavlaka","Griz","Puter","Čokolada za kuhanje","Kakao","Šećer","Suncokretovo ulje","Kore za pitu","Pavlaka","Sir","Limun","Maslinovo ulje","Krastavac","Mrkva","Rotkvica","Dajkon","Keleraba","Lovor","Biber","Peršun","Celer","Crveni luk","Paškanat","Šargarepa","Ćureći vrat","So","Mlijeko","Krompir","Jaja"]});
                });
            </script>
            <form id="search-form" method = "GET" class="test" action="{% url 'recepti' %}">
                    {% csrf_token %}
                <ul id="myTags" style="height:258px;">
                    <!-- Existing list items will be pre-added to the tags -->
                </ul>
                <input type="hidden" name="q" id="id_q" />
                <button type="submit" class="btn-success">PRETRAŽI</button>
            </form>
        </div>
    </div>

{% endblock %}

recepti/templates/recepti/login.html
{% extends 'recepti/base.html' %}
{% block title %}Prijavite se!{% endblock %}

{% block body %}

    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'prijavljivanje' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Korisničko ime</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Šifra</label></td>
                        <td><input id="id_password" name="password" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class="badge badge-warning">
                        Korisničko ime i šifra vam se ne poklapaju.
                        Pokušajte ponovo.
                    </p>
                {% endif %}
                <p align = 'center'>Nemate nalog? Napravite ga <a href = "{% url 'registracija' %}">ovdje</a></p>
                <input type="submit" value="Prijavite se" 
                       class="btn btn-primary pull-center" />
            </form>
        </div>
    </div>

{% endblock %}

recepti/templates/recepti/recepti.html
{% extends 'recepti/base.html' %}
{% block title %}Recepti{% endblock %}
{% load staticfiles %}

{% block body %}
    <div class="kontejner">
        <link rel="stylesheet" type="text/css" href="{% static 'recepti/recepti.css' %}" >

        {% if random_dorucak %}
        <h3 align = 'center' class="dorucak"> Za doručak mozete napraviti: </h3>
        <ul align = 'center' class = 'list-unstyled'>
            <a href = "{% url 'detalji' random_dorucak.id %}"><img src="{{random_dorucak.slika.url}}" width="600" height="400"></a><br/>
            <a href="{% url 'detalji' random_dorucak.id  %}">{{ random_dorucak.ime }}</a><br>
        </ul>
        {% endif %}

        {% if random_rucak %}
        <h3 align = 'center'> Za ručak mozete napraviti: </h3>
        <ul align = 'center' class = 'list-unstyled'>
            <a href = "{% url 'detalji' random_rucak.id %}"><img src="{{random_rucak.slika.url}}" width="600" height="400"></a><br/>
            <a href="{% url 'detalji' random_rucak.id  %}">{{ random_rucak.ime }}</a><br>
        </ul>
        {% endif %}

        {% if random_vecera %}
        <h3 align = 'center'> Za večeru mozete napraviti: </h3>
        <ul align = 'center' class = 'list-unstyled'>
            <a href = "{% url 'detalji' random_vecera.id %}"><img src="{{random_vecera.slika.url}}" width="600" height="400"></a><br/>
            <a href="{% url 'detalji' random_vecera.id  %}">{{ random_vecera.ime }}</a><br>
        </ul>
        {% endif %}

        {% if random_uzina %}
        <h3 align = 'center'> Za užinu mozete napraviti: </h3>
        <ul align = 'center' class = 'list-unstyled'>
            <a href = "{% url 'detalji' random_uzina.id %}"><img src="{{random_uzina.slika.url}}" width="600" height="400"></a><br/>
            <a href="{% url 'detalji' random_uzina.id  %}">{{ random_uzina.ime }}</a><br>
        </ul>
        {% endif %}

        <h3 align = 'center' class="svirecepti"> Svi recepti koje mozete napraviti sa sastojcima koje imate: </h3>
        <ul align = 'center' class = 'list-unstyled'>
            {% for jelo in recepti %}
                <a href = "{% url 'detalji' jelo.id %}"><img src="{{jelo.slika.url}}" width="600" height="400"></a><br/>
                <a href="{% url 'detalji' jelo.id %}"> {{ jelo.ime }} </a><br>
            {% endfor %}
        </ul>
    </div>

{% endblock %}

recepti/templates/recepti/registration_form.html
{% extends 'recepti/base.html' %}
{% block title %}Registrujte se!{% endblock %}

{% block body %}

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Registrujte se! </h3>
                        <form id="login-form" method="post" 
                        action="{% url 'registracija' %}">
                            {% csrf_token %}
                            <table class="table">
                                <tr>
                                    <td><label for="id_username">Korisničko ime</label></td>
                                    <td><input id="id_username" name="username" 
                                               type="text" class="form-control"></td>
                                </tr>
                                <tr>
                                    <td><label for="id_password">Šifra</label></td>
                                    <td><input id="id_password" name="password" 
                                               type="password" class="form-control"></td>
                                </tr>
                                <tr>
                                    <td><label for = "id_email">Email adresa</label></td>
                                    <td><input id = "id_email" name = "email"
                                               type = "text" class = "form-control"></td>

                                </tr>
                            </table>
                            {% if form.errors %}
                              {% for field in form %}
                                 {% for error in field.errors %}
                                     <div class="badge badge-warning">
                                     <strong>{{ error|escape }}</strong>
                                     </div><br/>
                                 {% endfor %}
                             {% endfor %}
                              {% for error in form.non_field_errors %}
                                 <div class="badge badge-warning">
                                 <strong>{{ error|escape }}</strong>
                                 </div><br/>
                              {% endfor %}
                            {% endif %}
                            <button type="submit" class="btn btn-success">Registruj se</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}